runtime: python37
env: standard 
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
 python_version: 3

#network:
#  instance_tag: tagname
#  name: cloudvpc 
#  subnetwork_name: cloudsubnet 

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 1
  max_instances: 20
  min_instances: 1
